import { Component, signal } from '@angular/core';
import { JobResponse } from '../../../shared/customer/modals/jobs.response';
import { JobCard } from './job-card/job-card';

@Component({
  selector: 'app-jobs-listing',
  imports: [JobCard],
  templateUrl: './jobs-listing.html',
  styleUrl: './jobs-listing.scss',
})
export class JobsListing {
  jobs = signal<JobResponse[]>([]);
  ngOnInit() {
    this.jobs.set([
      {
        id: 1,
        title: 'Senior Full Stack Developer',
        company: 'Ease-Ed Tech Solutions',
        location: 'Remote / Punjab, India',
        salary: '₹12L - ₹18L PA',
        type: 'Full-time',
        postedDate: '2 days ago',
        icon: 'bi-code-slash',
        description:
          'We are looking for an experienced developer with expertise in Angular and C#. You will lead the development of our core job portal features.',
      },
      {
        id: 2,
        title: 'UI/UX Designer',
        company: 'Creative Minds Studio',
        location: 'Amritsar, Punjab',
        salary: '₹8L - ₹12L PA',
        type: 'Contract',
        postedDate: '5 hours ago',
        icon: 'bi-palette',
        description:
          'Focus on creating high-fidelity mockups and ensuring the best user experience for mobile and web applications.',
      },
      {
        id: 3,
        title: 'Backend Engineer (C# / .NET)',
        company: 'CloudScale Systems',
        location: 'Chandigarh, India',
        salary: '₹15L - ₹22L PA',
        type: 'Full-time',
        postedDate: '1 week ago',
        icon: 'bi-database',
        description:
          'Design and implement scalable APIs and database schemas. Experience with Entity Framework Core is a must.',
      },
      {
        id: 4,
        title: 'Junior Frontend Developer',
        company: 'Startup Hub',
        location: 'Remote',
        salary: '₹5L - ₹7L PA',
        type: 'Internship',
        postedDate: 'Just now',
        icon: 'bi-layout-text-window',
        description:
          'Great opportunity for freshers to work with Angular 21 and PrimeNG. Work closely with senior developers to build responsive UIs.',
      },
      {
        id: 1,
        title: 'Senior Full Stack Developer',
        company: 'Ease-Ed Tech Solutions',
        location: 'Remote / Punjab, India',
        salary: '₹12L - ₹18L PA',
        type: 'Full-time',
        postedDate: '2 days ago',
        icon: 'bi-code-slash',
        description:
          'We are looking for an experienced developer with expertise in Angular and C#. You will lead the development of our core job portal features.',
      },
      {
        id: 2,
        title: 'UI/UX Designer',
        company: 'Creative Minds Studio',
        location: 'Amritsar, Punjab',
        salary: '₹8L - ₹12L PA',
        type: 'Contract',
        postedDate: '5 hours ago',
        icon: 'bi-palette',
        description:
          'Focus on creating high-fidelity mockups and ensuring the best user experience for mobile and web applications.',
      },
      {
        id: 3,
        title: 'Backend Engineer (C# / .NET)',
        company: 'CloudScale Systems',
        location: 'Chandigarh, India',
        salary: '₹15L - ₹22L PA',
        type: 'Full-time',
        postedDate: '1 week ago',
        icon: 'bi-database',
        description:
          'Design and implement scalable APIs and database schemas. Experience with Entity Framework Core is a must.',
      },
      {
        id: 4,
        title: 'Junior Frontend Developer',
        company: 'Startup Hub',
        location: 'Remote',
        salary: '₹5L - ₹7L PA',
        type: 'Internship',
        postedDate: 'Just now',
        icon: 'bi-layout-text-window',
        description:
          'Great opportunity for freshers to work with Angular 21 and PrimeNG. Work closely with senior developers to build responsive UIs.',
      },
      {
        id: 1,
        title: 'Senior Full Stack Developer',
        company: 'Ease-Ed Tech Solutions',
        location: 'Remote / Punjab, India',
        salary: '₹12L - ₹18L PA',
        type: 'Full-time',
        postedDate: '2 days ago',
        icon: 'bi-code-slash',
        description:
          'We are looking for an experienced developer with expertise in Angular and C#. You will lead the development of our core job portal features.',
      },
      {
        id: 2,
        title: 'UI/UX Designer',
        company: 'Creative Minds Studio',
        location: 'Amritsar, Punjab',
        salary: '₹8L - ₹12L PA',
        type: 'Contract',
        postedDate: '5 hours ago',
        icon: 'bi-palette',
        description:
          'Focus on creating high-fidelity mockups and ensuring the best user experience for mobile and web applications.',
      },
      {
        id: 3,
        title: 'Backend Engineer (C# / .NET)',
        company: 'CloudScale Systems',
        location: 'Chandigarh, India',
        salary: '₹15L - ₹22L PA',
        type: 'Full-time',
        postedDate: '1 week ago',
        icon: 'bi-database',
        description:
          'Design and implement scalable APIs and database schemas. Experience with Entity Framework Core is a must.',
      },
      {
        id: 4,
        title: 'Junior Frontend Developer',
        company: 'Startup Hub',
        location: 'Remote',
        salary: '₹5L - ₹7L PA',
        type: 'Internship',
        postedDate: 'Just now',
        icon: 'bi-layout-text-window',
        description:
          'Great opportunity for freshers to work with Angular 21 and PrimeNG. Work closely with senior developers to build responsive UIs.',
      },
      {
        id: 1,
        title: 'Senior Full Stack Developer',
        company: 'Ease-Ed Tech Solutions',
        location: 'Remote / Punjab, India',
        salary: '₹12L - ₹18L PA',
        type: 'Full-time',
        postedDate: '2 days ago',
        icon: 'bi-code-slash',
        description:
          'We are looking for an experienced developer with expertise in Angular and C#. You will lead the development of our core job portal features.',
      },
      {
        id: 2,
        title: 'UI/UX Designer',
        company: 'Creative Minds Studio',
        location: 'Amritsar, Punjab',
        salary: '₹8L - ₹12L PA',
        type: 'Contract',
        postedDate: '5 hours ago',
        icon: 'bi-palette',
        description:
          'Focus on creating high-fidelity mockups and ensuring the best user experience for mobile and web applications.',
      },
      {
        id: 3,
        title: 'Backend Engineer (C# / .NET)',
        company: 'CloudScale Systems',
        location: 'Chandigarh, India',
        salary: '₹15L - ₹22L PA',
        type: 'Full-time',
        postedDate: '1 week ago',
        icon: 'bi-database',
        description:
          'Design and implement scalable APIs and database schemas. Experience with Entity Framework Core is a must.',
      },
      {
        id: 4,
        title: 'Junior Frontend Developer',
        company: 'Startup Hub',
        location: 'Remote',
        salary: '₹5L - ₹7L PA',
        type: 'Internship',
        postedDate: 'Just now',
        icon: 'bi-layout-text-window',
        description:
          'Great opportunity for freshers to work with Angular 21 and PrimeNG. Work closely with senior developers to build responsive UIs.',
      },
      {
        id: 1,
        title: 'Senior Full Stack Developer',
        company: 'Ease-Ed Tech Solutions',
        location: 'Remote / Punjab, India',
        salary: '₹12L - ₹18L PA',
        type: 'Full-time',
        postedDate: '2 days ago',
        icon: 'bi-code-slash',
        description:
          'We are looking for an experienced developer with expertise in Angular and C#. You will lead the development of our core job portal features.',
      },
      {
        id: 2,
        title: 'UI/UX Designer',
        company: 'Creative Minds Studio',
        location: 'Amritsar, Punjab',
        salary: '₹8L - ₹12L PA',
        type: 'Contract',
        postedDate: '5 hours ago',
        icon: 'bi-palette',
        description:
          'Focus on creating high-fidelity mockups and ensuring the best user experience for mobile and web applications.',
      },
      {
        id: 3,
        title: 'Backend Engineer (C# / .NET)',
        company: 'CloudScale Systems',
        location: 'Chandigarh, India',
        salary: '₹15L - ₹22L PA',
        type: 'Full-time',
        postedDate: '1 week ago',
        icon: 'bi-database',
        description:
          'Design and implement scalable APIs and database schemas. Experience with Entity Framework Core is a must.',
      },
      {
        id: 4,
        title: 'Junior Frontend Developer',
        company: 'Startup Hub',
        location: 'Remote',
        salary: '₹5L - ₹7L PA',
        type: 'Internship',
        postedDate: 'Just now',
        icon: 'bi-layout-text-window',
        description:
          'Great opportunity for freshers to work with Angular 21 and PrimeNG. Work closely with senior developers to build responsive UIs.',
      },
      {
        id: 1,
        title: 'Senior Full Stack Developer',
        company: 'Ease-Ed Tech Solutions',
        location: 'Remote / Punjab, India',
        salary: '₹12L - ₹18L PA',
        type: 'Full-time',
        postedDate: '2 days ago',
        icon: 'bi-code-slash',
        description:
          'We are looking for an experienced developer with expertise in Angular and C#. You will lead the development of our core job portal features.',
      },
      {
        id: 2,
        title: 'UI/UX Designer',
        company: 'Creative Minds Studio',
        location: 'Amritsar, Punjab',
        salary: '₹8L - ₹12L PA',
        type: 'Contract',
        postedDate: '5 hours ago',
        icon: 'bi-palette',
        description:
          'Focus on creating high-fidelity mockups and ensuring the best user experience for mobile and web applications.',
      },
      {
        id: 3,
        title: 'Backend Engineer (C# / .NET)',
        company: 'CloudScale Systems',
        location: 'Chandigarh, India',
        salary: '₹15L - ₹22L PA',
        type: 'Full-time',
        postedDate: '1 week ago',
        icon: 'bi-database',
        description:
          'Design and implement scalable APIs and database schemas. Experience with Entity Framework Core is a must.',
      },
      {
        id: 4,
        title: 'Junior Frontend Developer',
        company: 'Startup Hub',
        location: 'Remote',
        salary: '₹5L - ₹7L PA',
        type: 'Internship',
        postedDate: 'Just now',
        icon: 'bi-layout-text-window',
        description:
          'Great opportunity for freshers to work with Angular 21 and PrimeNG. Work closely with senior developers to build responsive UIs.',
      },
      {
        id: 1,
        title: 'Senior Full Stack Developer',
        company: 'Ease-Ed Tech Solutions',
        location: 'Remote / Punjab, India',
        salary: '₹12L - ₹18L PA',
        type: 'Full-time',
        postedDate: '2 days ago',
        icon: 'bi-code-slash',
        description:
          'We are looking for an experienced developer with expertise in Angular and C#. You will lead the development of our core job portal features.',
      },
      {
        id: 2,
        title: 'UI/UX Designer',
        company: 'Creative Minds Studio',
        location: 'Amritsar, Punjab',
        salary: '₹8L - ₹12L PA',
        type: 'Contract',
        postedDate: '5 hours ago',
        icon: 'bi-palette',
        description:
          'Focus on creating high-fidelity mockups and ensuring the best user experience for mobile and web applications.',
      },
      {
        id: 3,
        title: 'Backend Engineer (C# / .NET)',
        company: 'CloudScale Systems',
        location: 'Chandigarh, India',
        salary: '₹15L - ₹22L PA',
        type: 'Full-time',
        postedDate: '1 week ago',
        icon: 'bi-database',
        description:
          'Design and implement scalable APIs and database schemas. Experience with Entity Framework Core is a must.',
      },
      {
        id: 4,
        title: 'Junior Frontend Developer',
        company: 'Startup Hub',
        location: 'Remote',
        salary: '₹5L - ₹7L PA',
        type: 'Internship',
        postedDate: 'Just now',
        icon: 'bi-layout-text-window',
        description:
          'Great opportunity for freshers to work with Angular 21 and PrimeNG. Work closely with senior developers to build responsive UIs.',
      },
    ]);
  }
}
